FROM python:3.8.7
LABEL Anton Klyukin <antonklyukin@gmail.com>

ENV INSTALL_PATH /my-blog
RUN mkdir -p ${INSTALL_PATH}

WORKDIR ${INSTALL_PATH}

COPY requirements.txt requirements.txt
COPY ./my-blog/. ${INSTALL_PATH}

RUN pip install -r requirements.txt

EXPOSE 5000



CMD python app.py
